AL-7839 - clear cached styles for features with polygon geometries when edited
yottaltd/alloy-map pull request #112
Opened 2020-09-03 12:38 UTC by OlegRayskiy

2020-09-03 12:45 UTC, OlegRayskiy commented
Ignore the error, just unit test pipeline step is failing, since that PR hasn't been merged in yet

2020-10-05 22:37 UTC, cmcnicholas commented
needs merging and conflicts resolving @OlegRayskiy

2020-10-06 09:25 UTC, OlegRayskiy commented
> needs merging and conflicts resolving @OlegRayskiy

done

2020-10-07 10:48 UTC, cmcnicholas requested changes

2020-10-07 10:48 UTC, cmcnicholas commented on src/map/styles/cache/AlloyStyleCache.ts
> +  public clear(id: string): void {
this won't work because we don't have control of id's not to mention is expensive to match by string includes.

by control of id's I mean our cache keys could be.

123.456
890.123
999.000

but an "id" m,ight be 123 however it would match any part of the key

2020-10-07 10:48 UTC, cmcnicholas commented on src/map/styles/cache/AlloyStyleCache.ts
> +  public clear(id: string): void {
I don't see a way to fix this except either:

- clear entire cache
- make cache keys an object rather than a string e.g.

```ts
{
  key: "stringified key as before",
  parts: {
    featureId: "x",
    styleThing: "y",
    isBig: true,
  }
}
```

probably needs a type or discriminator

2020-10-07 16:03 UTC, cmcnicholas approved these changes

2020-10-07 16:04 UTC, merged